/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import conexion.consultaBase;
import consultas.DesafiliacionConsulta;
import consultas.PersonaConsulta;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import entidades.persona;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vladimir
 */
public class Desafiliacion extends javax.swing.JFrame {

    PersonaConsulta personaConsulta = new PersonaConsulta();
    DesafiliacionConsulta desafiliacionConsulta = new DesafiliacionConsulta();
    /**
     * Creates new form desafiliacion
     */
    public Desafiliacion() {
        initComponents();
        jButton4.setEnabled(false);
        req6.setVisible(false);
        req7.setVisible(false);
    }
    
    int cont = 0;
    
    public void validar(){
        if(jTextField6.getText().equals("")){req6.setVisible(true); cont++;} else{req6.setVisible(false);}
        if(jTextField16.getText().equals("") || jTextField15.getText().equals("") || jTextField7.getText().equals("")){req7.setVisible(true); cont++;} else{req7.setVisible(false);}  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        codVoluntario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        region = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comite = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nacimiento = new javax.swing.JLabel();
        adas = new javax.swing.JLabel();
        ingreso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        req6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        req7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPAJU");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(821, 709));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desafiliación");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 26, 818, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Escriba la cédula del voluntario a desafiliar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        cedula.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cedula.setToolTipText("");
        cedula.setBorder(null);
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 200, 30));

        botonBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        botonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 110, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 200, 20));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Código de voluntario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        codVoluntario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(codVoluntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Región:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        region.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(region, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Comité:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        comite.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(comite, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 210, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Fecha de Nacimiento: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        nacimiento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 140, -1));

        adas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        adas.setForeground(new java.awt.Color(255, 0, 51));
        adas.setText("Fecha de Ingreso: ");
        jPanel1.add(adas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        ingreso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 150, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Motivo de desafiliación:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, -1));

        jLabel29.setText("AAAA");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        req6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        req6.setText("*Dato requerido*");
        jPanel1.add(req6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jTextField6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 450, 31));

        jTextField15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 37, 31));

        jTextField16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 69, 31));

        jLabel16.setText("DD");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel28.setText("MM");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Fecha de desafiliación:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        req7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        req7.setText("*Dato requerido*");
        jPanel1.add(req7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jTextField7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 37, 31));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/logo pequeno.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel2)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 660, 815, -1));

        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jButton4.setText("Desafiliar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 597, 162, 30));

        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jButton5.setText("Menu Principal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 597, 162, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 709));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
            (caracter > '9')) &&
        (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
        int largo = cedula.getText().length()+1;
        if(largo > 0){
            botonBuscar.setEnabled(true);
        }
        else{
            botonBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_cedulaKeyTyped

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        persona person = personaConsulta.obtenerPersona("", Integer.parseInt(cedula.getText()), "Activo");
        if(person.getNombre() != null){
            if(person.getEsAsociado().equals("Si")){
                int resp = JOptionPane.showConfirmDialog(null, "     Este voluntari@ es asociad@ activo\n\n ¿Esta seguro que quiere continuar con la desafiliación?", "Alerta!", JOptionPane.YES_NO_OPTION);
                if(resp == 0){
                    nombre.setText(person.getNombre());
                    region.setText(person.getRegion());
                    comite.setText(person.getComite());
                    codVoluntario.setText(person.getCodigoVoluntario());

                    //Fecha de Nacimiento
                    StringTokenizer tokensNacimiento = new StringTokenizer(person.getFechaNacimiento(), "-");
                    String ano1 = tokensNacimiento.nextToken();
                    String mes1 = tokensNacimiento.nextToken();
                    String dia1 = tokensNacimiento.nextToken();
                    nacimiento.setText(dia1+"/"+mes1+"/"+ano1);

                    //Fecha de Ingreso
                    StringTokenizer tokensIngreso = new StringTokenizer(person.getFechaIngreso(), "-");
                    String ano2 = tokensIngreso.nextToken();
                    String mes2 = tokensIngreso.nextToken();
                    String dia2 = tokensIngreso.nextToken();
                    ingreso.setText(dia2+"/"+mes2+"/"+ano2);
                    jButton4.setEnabled(true);
                }
                else{
                    MenuTramites abrir = new MenuTramites();
                    abrir.setLocationRelativeTo(null);
                    abrir.setVisible(true);
                    this.setVisible(false);
                }
            }
            else{
                    nombre.setText(person.getNombre());
                    region.setText(person.getRegion());
                    comite.setText(person.getComite());
                    codVoluntario.setText(person.getCodigoVoluntario());

                    //Fecha de Nacimiento
                    StringTokenizer tokensNacimiento = new StringTokenizer(person.getFechaNacimiento(), "-");
                    String ano1 = tokensNacimiento.nextToken();
                    String mes1 = tokensNacimiento.nextToken();
                    String dia1 = tokensNacimiento.nextToken();
                    nacimiento.setText(dia1+"/"+mes1+"/"+ano1);

                    //Fecha de Ingreso
                    StringTokenizer tokensIngreso = new StringTokenizer(person.getFechaIngreso(), "-");
                    String ano2 = tokensIngreso.nextToken();
                    String mes2 = tokensIngreso.nextToken();
                    String dia2 = tokensIngreso.nextToken();
                    ingreso.setText(dia2+"/"+mes2+"/"+ano2);
                    jButton4.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontro ningun resultado\n\n Ingrese otra cedula");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonBuscarKeyTyped

    }//GEN-LAST:event_botonBuscarKeyTyped

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cont = 0;
        validar();
        if(cont==0){    
            String cedu = cedula.getText();
            String fecha = jTextField16.getText()+"-"+jTextField15.getText()+"-"+jTextField7.getText();
            String motivo = jTextField6.getText();
            int ceduNum = Integer.parseInt(cedu);
            if( desafiliacionConsulta.desafiliarPersona(ceduNum, fecha, motivo) ){
                JOptionPane.showMessageDialog(null, "Desafiliacion correcta");
                Menu abrir = new Menu();
                abrir.setLocationRelativeTo(null);
                abrir.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Aun falta datos por rellenar");
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        Menu abrir = new Menu();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desafiliacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Desafiliacion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adas;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel codVoluntario;
    private javax.swing.JLabel comite;
    private javax.swing.JLabel ingreso;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel nacimiento;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel region;
    private javax.swing.JLabel req6;
    private javax.swing.JLabel req7;
    // End of variables declaration//GEN-END:variables
}
