/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import conexion.consultaBase;
import consultas.ComiteConsulta;
import consultas.DesafiliacionConsulta;
import consultas.PersonaConsulta;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;
import entidades.desafiliado;
import entidades.persona;

/**
 *
 * @author Vladimir
 */
public final class DesafiliacionLista extends javax.swing.JFrame {

    /**
     *
     * Creates new form buscarPersona
     */
    
    String nombre;
    consultaBase con = new consultaBase();
    ComiteConsulta comiteConsulta = new ComiteConsulta();
    PersonaConsulta personaConsulta = new PersonaConsulta();
    DesafiliacionConsulta desafiliacionConsulta = new DesafiliacionConsulta();
    
    public DesafiliacionLista() {
        initComponents();
        botonBuscar.setEnabled(false);
        inicializarLista();
        
        
        //this.setMinimumSize(new Dimension(904, 190)); 
    }
    
    public void inicializarLista(){
        ArrayList<String> lista = this.desafiliacionConsulta.obtenerNombresDesafiliado("");
        Calendar cal= Calendar.getInstance();
        nombreSele.removeAll();
        DefaultListModel modelo = new DefaultListModel();
        for(int i = 0; i < lista.size(); i++){
                modelo.addElement(lista.get(i));
        }
        nombreSele.setModel(modelo);
        
        int year= cal.get(Calendar.YEAR);
        
        /*Datos de los anos*/
        jComboBox6.addItem(" ");
        for(int i=0; i < 21 ; i++){
            jComboBox6.addItem( String.valueOf(year-i) );
        }
        
        /*Datos de las regiones*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombreSele = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPAJU");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setText("Lista de Desafiliados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Año");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 50, 30));

        botonBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 100, 40));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N

        nombreSele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreSele.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        nombreSele.setToolTipText("");
        nombreSele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreSeleMousePressed(evt);
            }
        });
        nombreSele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreSeleKeyPressed(evt);
            }
        });
        nombreSele.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                nombreSeleValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(nombreSele);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 500, 280));

        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jButton6.setText("Menu Principal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 162, 30));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 3, 30, 574));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/logo pequeno.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("<html><p align=\"center\">Filtro por</p><p align=\"center\">fecha de desafiliación </p></html>");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, 60));

        jComboBox5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox5.setToolTipText("");
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox5MousePressed(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 140, 31));

        jComboBox6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox6.setToolTipText("");
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox6MouseClicked(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 100, 31));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Seleccione para buscar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Mes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 60, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Comité");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 60, 30));

        jComboBox7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "" }));
        jComboBox7.setToolTipText("");
        jComboBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox7ItemStateChanged(evt);
            }
        });
        jComboBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox7MousePressed(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 170, 31));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Región");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 60, 30));

        jComboBox8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "San Jose", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limon", "Zona Sur", "Zona Norte" }));
        jComboBox8.setToolTipText("");
        jComboBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox8MousePressed(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 170, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 835, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        persona person = personaConsulta.obtenerPersona(nombre, 0, "Desafiliado");
        desafiliado desafilia = desafiliacionConsulta.obtenerPersonaDesafiliada(person.getCedula());
        desafilia.setPersona(person);
        if(desafilia.getPersona().getNombre() != null){
            InfoPersonaDesafiliada abrir = new InfoPersonaDesafiliada(desafilia);
            abrir.setLocationRelativeTo(null);
            abrir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void nombreSeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreSeleKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nombreSeleKeyPressed

    private void nombreSeleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_nombreSeleValueChanged
 
    }//GEN-LAST:event_nombreSeleValueChanged

    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Menu abrir = new Menu();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nombreSeleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreSeleMousePressed
        String hola = nombreSele.getSelectedValue();
        
        StringTokenizer tokensNombre = new StringTokenizer(hola, "-");
        nombre = tokensNombre.nextToken();
        nombre = nombre.substring(0, nombre.length() - 1);
        botonBuscar.setEnabled(true);
    }//GEN-LAST:event_nombreSeleMousePressed

    private void creacionQuery(){
        ArrayList<String> lista = new ArrayList<>();
        String query = "";
        Boolean and = false;
        Boolean where = true;
        
        if( jComboBox5.getSelectedIndex() < 10 && jComboBox5.getSelectedIndex() > 0){
            if(where){ query += "where "; where = false; }
            query += "fechaDesafiliacion like '____-0" + jComboBox5.getSelectedIndex() + "%' ";
            and = true;
        }
        else if( jComboBox5.getSelectedIndex() > 9 ){
            if(where){ query += "where "; where = false; }
            query += " fechaDesafiliacion like '____-" + jComboBox5.getSelectedIndex() + "%' ";
            and = true;
        }
        
        
        if(jComboBox6.getSelectedIndex() != 0){
            if(where){ query += "where "; where = false; }
            if(and){ query += "and "; }
            query += "fechaDesafiliacion like '" + jComboBox6.getSelectedItem().toString() + "%' ";
            and = true;
        }
        
        
        if(jComboBox8.getSelectedIndex() != 0){
            if(where){ query += "where "; where = false; }
            if(and){ query += "and "; }
            query += "r.nombre = '" + jComboBox8.getSelectedItem().toString() + "' ";
            and = true;
        }

        jComboBox7.addItem("");
        if(jComboBox7.getSelectedIndex() != 0){
            if(where){ query += "where "; where = false; }
            if(and){ query += "and "; }
            query += "c.nombre = '" + jComboBox7.getSelectedItem().toString() + "' ";
        }
        jComboBox7.removeItem("");

        lista = this.desafiliacionConsulta.obtenerNombresDesafiliado(query);
        nombreSele.removeAll();
        DefaultListModel modelo = new DefaultListModel();
        for(int i = 0; i < lista.size(); i++){
                modelo.addElement(lista.get(i));
        }
        nombreSele.setModel(modelo);
        
        botonBuscar.setEnabled(false);
    }
    
    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        this.creacionQuery();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MousePressed

    }//GEN-LAST:event_jComboBox5MousePressed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        this.creacionQuery();
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7MousePressed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        //String region = jComboBox8.getSelectedItem().toString();
        jComboBox7.removeAllItems();
        ArrayList<String> listaComites = new ArrayList<>();
        listaComites = comiteConsulta.obtenerComitesXRegion(jComboBox8.getSelectedIndex());
        jComboBox7.addItem(" ");
        for(int i=0; i < listaComites.size(); i++){
            jComboBox7.addItem(listaComites.get(i));
        }
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8MousePressed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        this.creacionQuery();
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseClicked

    }//GEN-LAST:event_jComboBox6MouseClicked

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged

    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jComboBox7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox7ItemStateChanged
        
    }//GEN-LAST:event_jComboBox7ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesafiliacionLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesafiliacionLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesafiliacionLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesafiliacionLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesafiliacionLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> nombreSele;
    // End of variables declaration//GEN-END:variables
}
