/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import conexion.consultaBase;
import consultas.CargoConsulta;
import consultas.ComiteConsulta;
import consultas.RegionConsulta;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author Vladimir
 */
public class MenuFiltro extends javax.swing.JFrame {

    consultaBase conexion = new consultaBase();
    CargoConsulta cargoConsulta = new CargoConsulta();
    RegionConsulta regionConsulta = new RegionConsulta();
    ComiteConsulta comiteConsulta = new ComiteConsulta();
    
    public MenuFiltro() {
        initComponents();
        jComboBox9.setVisible(false);
        jLabel9.setVisible(false);
        llenarDatos();
    }
    
    
    public void llenarDatos(){
        consultaBase con = new consultaBase();
        Calendar cal= Calendar.getInstance();

        
        /*Datos del cargo*/
        ArrayList<String> lista = new ArrayList<>();
        lista = cargoConsulta.obtenerCargo();
        jComboBox2.addItem("");
        for(int i=0; i < lista.size(); i++){
            jComboBox2.addItem(lista.get(i));
        } 
        int year= cal.get(Calendar.YEAR);
        /*Datos de los anos*/
        jComboBox6.addItem("");
        for(int i=0; i < 21 ; i++){
            jComboBox6.addItem( String.valueOf(year-i) );
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        aleman = new javax.swing.JCheckBox();
        ingles = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        espanol = new javax.swing.JCheckBox();
        portugues = new javax.swing.JCheckBox();
        frances = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        mandarin = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filtro de información");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 30, 1044, -1));

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/principalCRJ.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 804, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 682, 1044, -1));

        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jButton5.setText("Filtrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 150, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Fecha de ingreso:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, 30));

        aleman.setBackground(new java.awt.Color(255, 255, 255));
        aleman.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        aleman.setText("Alemán");
        jPanel1.add(aleman, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        ingles.setBackground(new java.awt.Color(255, 255, 255));
        ingles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ingles.setText("Inglés");
        jPanel1.add(ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Género:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, 30));

        espanol.setBackground(new java.awt.Color(255, 255, 255));
        espanol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        espanol.setText("Español");
        jPanel1.add(espanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        portugues.setBackground(new java.awt.Color(255, 255, 255));
        portugues.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        portugues.setText("Portugués");
        jPanel1.add(portugues, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        frances.setBackground(new java.awt.Color(255, 255, 255));
        frances.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        frances.setText("Francés");
        frances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                francesActionPerformed(evt);
            }
        });
        jPanel1.add(frances, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Idioma(s):");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, 30));

        mandarin.setBackground(new java.awt.Color(255, 255, 255));
        mandarin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mandarin.setText("Mandarín");
        mandarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandarinActionPerformed(evt);
            }
        });
        jPanel1.add(mandarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Edad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jComboBox9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox9.setToolTipText("");
        jComboBox9.setName("cmbRegion"); // NOI18N
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 34));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel19.setText("Región:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jComboBox10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 221, 34));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel20.setText("Comité:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 30));

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 200, 30));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel24.setText("Cargo:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("hasta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 50, 30));

        jComboBox11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "San Jose", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limon", "Zona Sur", "Zona Norte" }));
        jComboBox11.setToolTipText("");
        jComboBox11.setName("cmbRegion"); // NOI18N
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, 34));

        jComboBox12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        jComboBox12.setToolTipText("");
        jComboBox12.setName("cmbRegion"); // NOI18N
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 60, 34));

        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jButton6.setText("<html><p align=\"center\">Rango</p><p align=\"center\">de edad</p></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, 50));

        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jButton7.setText("Menú principal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Femenino" }));
        jComboBox4.setToolTipText("");
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 158, 31));

        jComboBox5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox5.setToolTipText("");
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 110, 31));

        jComboBox6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBox6.setToolTipText("");
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 80, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        String query = "";
        boolean flagAnd = false;
        
        if( !"".equals(jComboBox11.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            query += "r.nombre = '" + jComboBox11.getSelectedItem().toString() + "' ";
            flagAnd = true;
            
        } 
        if( !"".equals(jComboBox10.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            query += "c.nombre = '" + jComboBox10.getSelectedItem().toString() + "' ";
            flagAnd = true;
        } 
        if( !"".equals(jComboBox4.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            query += "p.genero = '" + jComboBox4.getSelectedItem().toString() + "' ";
            flagAnd = true;
        }
        
        if( !"".equals(jComboBox12.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            if(jButton6.isVisible()){
                query += "p.edad = " + jComboBox12.getSelectedItem().toString();
            }
            else{
                query += "p.edad between " + jComboBox12.getSelectedItem().toString() + " and " + jComboBox9.getSelectedItem().toString() + " ";
            }
            
            flagAnd = true;
        } 
        if( !"".equals(jComboBox2.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            query += "ca.nombre = '" + jComboBox2.getSelectedItem().toString() + "' ";
            flagAnd = true;
        }
        if( !"".equals(jComboBox2.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            query += "ca.nombre = '" + jComboBox2.getSelectedItem().toString() + "' ";
            flagAnd = true;
        }
        if( espanol.isSelected() ){
            if(flagAnd){
                query += "and ";
            }
            query += "i.espanol = 1 ";
            flagAnd = true;
        }
        if( ingles.isSelected() ){
            if(flagAnd){
                query += "and ";
            }
            query += "i.ingles = 1 ";
            flagAnd = true;
        }
        if( portugues.isSelected() ){
            if(flagAnd){
                query += "and ";
            }
            query += "i.portugues = 1 ";
            flagAnd = true;
        }
        if( aleman.isSelected() ){
            if(flagAnd){
                query += "and ";
            }
            query += "i.aleman = 1 ";
            flagAnd = true;
        }
        if( frances.isSelected() ){
            if(flagAnd){
                query += "and ";
            }
            query += "i.frances = 1 ";
            flagAnd = true;
        }if( mandarin.isSelected() ){
            if(flagAnd){
                query += "and ";
            }
            query += "i.mandarin = 1 ";
            flagAnd = true;
        }
        
        if( !"".equals(jComboBox6.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            query += "p.fechaIngreso like '" + jComboBox6.getSelectedItem().toString() + "%' ";
            flagAnd = true;
        }
        if( !"".equals(jComboBox5.getSelectedItem().toString()) ){
            if(flagAnd){
                query += "and ";
            }
            if( jComboBox5.getSelectedIndex() < 10 ){
                query += "p.fechaIngreso like '____-0" + jComboBox5.getSelectedIndex() + "%' ";
            }else{
                query += "p.fechaIngreso like '____-" + jComboBox5.getSelectedIndex() + "%' ";
            }
            
            flagAnd = true;
        }
       
        consultaBase con = new consultaBase();
        
        con.filtar(query);
       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void francesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_francesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_francesActionPerformed

    private void mandarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandarinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mandarinActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        jComboBox10.removeAllItems();
        ArrayList<String> lista;
        lista = comiteConsulta.obtenerComitesXRegion(regionConsulta.obtenerRegionId(jComboBox11.getSelectedItem().toString()));
        jComboBox10.addItem("");
        for(int i=0; i < lista.size(); i++){
            jComboBox10.addItem(lista.get(i));
        }
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
        int numSeleccionado;
        if("".equals(jComboBox12.getSelectedItem().toString())){
            numSeleccionado = 0;
        }
        else{
            numSeleccionado = Integer.parseInt(jComboBox12.getSelectedItem().toString());
            jComboBox9.removeAllItems();
            for(int i=numSeleccionado; i < 40; i++){
                jComboBox9.addItem( String.valueOf(i+1) );
            }
        }  
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jComboBox9.setVisible(true);
        jLabel9.setVisible(true);
        jButton6.setVisible(false);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aleman;
    private javax.swing.JCheckBox espanol;
    private javax.swing.JCheckBox frances;
    private javax.swing.JCheckBox ingles;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox mandarin;
    private javax.swing.JCheckBox portugues;
    // End of variables declaration//GEN-END:variables
}
